### ISSUE TITLE
Parallel test support?

### ISSUE THREAD

**Issue by joffrey-bion** [crossbario/autobahn-testsuite#119]
Does the autobahn test suite support parallel testing?

I'm using the docker image for unit tests in a multiproject build, which may run in parallel.
It seems the test cases themselves go fine but when I try to call `/getCaseStatus` I sometimes don't get a proper text frame back (timeout while waiting, or connection abruptly closed).

**Comment by oberstet** [comment]
it wasn't designed for parallel operation. the iteration through all test cases works by incrementing an internal index ... I seem to remember
