### ISSUE TITLE
Minecraft websockets' differential vs standard implementation that passes Autobahn?

### ISSUE THREAD

**Issue by ylluminate** [crossbario/autobahn-testsuite#124]
Curious, recently someone mentioned, without details, that they are finding that a library that passes Autobahn websocket tests still will not work with Minecraft websockets requirements. I found that peculiar and before researching it further I wanted to see if anyone here had seen something similar or such an analysis wherein the differential between normal websockets implementations that pass all Autobahn tests might still fail Minecraft's websocket requirements?

As far as I understood it, this should not be the case and Minecraft requirements should be simply a subset, or inclusive of, a standard websocket implementation...

**Comment by ylluminate** [comment]
@oberstet please advise: the forums are no longer functional, eg:
* the old forum at https://groups.google.com/g/autobahnws no longer accepts posts.
* the new forum linked to from the Google Groups page (and not on the Github page as far as I can see) at https://forum.crossbar.io/ is not functional:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/WnuDvLog/03f6f53e-38d2-4eff-a5ac-80c46c23d085.png?v=0b608bbae5aa8a8c7ab7614435e4224e)

**Comment by oberstet** [comment]
sorry, this was moved (again) to https://crossbar.discourse.group/ where it runs hosted on public discourse and not company servers (which are retired)

apparantely, the link in the repo here was still broken .. fixed that:

https://github.com/crossbario/autobahn-testsuite/commit/09cfbf74b0c8e335c6fc7df88e5c88349ca66879

----

rgd Minecraft: no idea. thing is: this testsuite will test websocket compliance extensively, and a library passing should be able to connect to Minecraft. there are a couple of caveats:
* websocket intermediaries like proxies
* TLS certificates
* enabled websocket extensions
also, websocket begins with a HTTP prelude, and this testsuite (mostly) only tests everything after the prelude (the actual websocket message protocol)

I would enable max debug level in your client library and record what happens and where and how it fails when connecting to your minecraft server.
