### ISSUE TITLE
Test that clients read Upgrade and Connection headers as case-insensitive ASCII

### ISSUE THREAD

**Issue by deanveloper** [crossbario/autobahn-testsuite#131]
Under section 4.1: https://datatracker.ietf.org/doc/html/rfc6455#section-4.1
```
   2.  If the response lacks an |Upgrade| header field or the |Upgrade|
       header field contains a value that is not an ASCII case-
       insensitive match for the value "websocket", the client MUST
       _Fail the WebSocket Connection_.

   3.  If the response lacks a |Connection| header field or the
       |Connection| header field doesn't contain a token that is an
       ASCII case-insensitive match for the value "Upgrade", the client
       MUST _Fail the WebSocket Connection_.
```

I made my own autobahn-compliant websocket client but it immediately failed because https://ws.discord.gg/ replies with "Connection: upgrade"

**Comment by deanveloper** [comment]
Autobahn also doesn't test that clients do case-insensitive checks for header names

**Comment by oberstet** [comment]
just a few quick comments:

* related: https://github.com/crossbario/autobahn-testsuite/issues/82
* AutobahnPython WebSocket opening handshake / header parsing code is here: https://github.com/crossbario/autobahn-python/blob/7bc85b34e200640ab98a41cfddb38267f39bc92e/autobahn/websocket/protocol.py#L2592
* specifically, HTTP header parsing code (which is case insensitive according to spec) is here: https://github.com/crossbario/autobahn-python/blob/7bc85b34e200640ab98a41cfddb38267f39bc92e/autobahn/websocket/protocol.py#L255

> Autobahn also doesn't seem to test that clients do case-insensitive checks for header names

it does: https://github.com/crossbario/autobahn-python/blob/7bc85b34e200640ab98a41cfddb38267f39bc92e/autobahn/websocket/protocol.py#L2697
