### ISSUE TITLE
Add testcase RFC7692 (permessage-deflate) Section 7.2.3.6

### ISSUE THREAD

**Issue by joakime** [crossbario/autobahn-testsuite#59]
It appears that many implementations have Section 7.2.3.6 of permessage-deflate wrong.
https://tools.ietf.org/html/rfc7692#section-7.2.3.6

If two messages (from server to client) is sent like the following ...

TEXT ("Hello") / rsv1 / fin==false
  41 0b f2 48 cd c9 c9 07 00 00 00 ff ff
CONTINUATION (1 byte following Section 7.2.3.6) / rsv1 / fin==true
  c0 01 00
TEXT ("World") / rsv1 / fin==false
  41 0b 0a cf 2f ca 49 01 00 00 00 ff ff
CONTINUATION (1 byte following Section 7.2.3.6) / rsv1 / fin==true
  c0 01 00

Most browser will fail to parse/decode these 4 frames into 2 messages per the rules in Section 7.2.3.6
Some 3rd party websocket libraries will also fail.

**Comment by joakime** [comment]
Attaching wireshark capture of this bad behavior in Firefox and Chrome (so you can see the individual frames along with the whole negotiation step as well)

[websocket-premessage-deflate-7.2.3.6-bug.zip](https://github.com/crossbario/autobahn-testsuite/files/92657/websocket-premessage-deflate-7.2.3.6-bug.zip)

**Comment by oberstet** [comment]
It's unlikely that I find time to work on this in 2016. But of course, a test case would make up a nice PR;)

**Comment by joakime** [comment]
Filed a bug at chrome about this too ... 
https://code.google.com/p/chromium/issues/detail?id=580290

I'm curious to see where this will go.
I hybi list still around?  Should I bring this up there?

**Comment by oberstet** [comment]
@joakime yep, the Hybi list is still around - only the WG was closed.

**Comment by oberstet** [comment]
Accroding to above linked issue, this seem to have been a Jetty bug which is fixed now. Closing,
