### ISSUE TITLE
HTTP response parser fails to decode Latin-1

### ISSUE THREAD

**Issue by alexhultman** [crossbario/autobahn-testsuite#61]
I send char 181 in my response header which is decoded properly in Edge, Firefox, Chrome and seems to be historically supported. Autobahn crashes due to failed Utf-8 parsing. The header is not supposed to be decoded as Utf-8, and it is perfectly legal to send char 181.

**Comment by oberstet** [comment]
This was fixed in AutobahnPython some time ago https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L268

But the testsuite uses an old version of AutobahnPython - which doesn't have it fixed ..

**Comment by oberstet** [comment]
wont fix. testsuite will stay at the pinned autobahn version
