### ISSUE TITLE
Non-zero exit code from wstest

### ISSUE THREAD

**Issue by provegard** [crossbario/autobahn-testsuite#68]
I'm using `wstest -m fuzzingclient`. However, wstest always exits with exit code 0, regardless of the actual test outcome. It would be useful if wstest exited with a non-zero exits code if any failures occurred during the test run.

**Comment by oberstet** [comment]
the fuzzingclient runs against a _set_ of servers. returning non-zero (at the end, when wstest exits) when any single test on any of the servers fails isn't really useful IMO.

I'd recommend reading the generated summary report (which is also generated in JSON format).

using that, you can access per-server (and per-server + per-test) success/failure info, and depending on that, fail your CI or what ..

**Comment by nhooyr** [comment]
This would be really nice as a flag as I expect most users would consider any test failure to make `wstest` return a non zero.
