### ISSUE TITLE
Case 7.1.6 

### ISSUE THREAD

**Issue by neon12345** [crossbario/autobahn-testsuite#70]
Is there a bug in Case 7.1.6. Why is the 256k message not expected in the result? And the 'Hello World!' message is not mentioned in the description?

Expected:
{'NON-STRICT': [], 'OK': [('message', u'Hello World!', False)]}

Observed:
[('message', u'BAsd7&jh23BAsd7&jh23BAsd7&jh23BAsd7&jh23BAsd7&jh23BAsd7&jh23BAsd ...', False), ('message', u'Hello World!', False)]

**Comment by oberstet** [comment]
> Why is the 256k message not expected in the result? 

because it is implementation specific (the whole point of this test), which is the reason why the test is marked as "informational"

**Comment by neon12345** [comment]
It adds a bit of confusion to "informational".
