### ISSUE TITLE
Fuzzingclient docs

### ISSUE THREAD

**Issue by Paxa** [crossbario/autobahn-testsuite#72]
Where to find documentation on how fuzzingserver and fuzzingclient should work?

I also try to use echoclient, run as `wstest -m echoclient -w ws://127.0.0.1:9001`. Test only connects but don't send any messages

**Comment by oberstet** [comment]
https://github.com/crossbario/autobahn-testsuite

**Comment by Paxa** [comment]
Thank you, can you point to a specific section of that page?
