### ISSUE TITLE
Boost.Beast uses Autobahn|Testsuite

### ISSUE THREAD

**Issue by vinniefalco** [crossbario/autobahn-testsuite#76]
Beast was ACCEPTED into Boost on July 2017, without conditions:
The library will become part of the Boost 1.66.0 release in December:
https://github.com/boostorg/beast

You can see the Autobahn|Testsuite results here:
http://vinniefalco.github.io/autobahn/index.html

Can we please add Beast to the list of Autobahn|Testsuite users?

Thanks!

**Comment by oberstet** [comment]
Sure!

Congrats on the acceptance to Boost mainline .. Boost.Beast looks nice, very complete and with a lot of community activity. Awesome!

https://github.com/crossbario/autobahn-testsuite/commit/261012c76e300d2168b22991bb818e5c705f7cbd

**Comment by vinniefalco** [comment]
\blush, thanks
