### ISSUE TITLE
Test names are based on dict iteration order, so they get scrambled by hash randomization

### ISSUE THREAD

**Issue by njsmith** [crossbario/autobahn-testsuite#80]
Currently, the names of the 12.X tests are assigned [based on the iteration order](https://github.com/crossbario/autobahn-testsuite/blob/ea60ebf184868d0fe5d43f6e03f1154d5b9e8141/autobahntestsuite/autobahntestsuite/case/case12_x_x.py#L211) of a [dictionary](https://github.com/crossbario/autobahn-testsuite/blob/ea60ebf184868d0fe5d43f6e03f1154d5b9e8141/autobahntestsuite/autobahntestsuite/case/case12_x_x.py#L57-L88). But if hash randomization enabled via the `-R` switch or setting `PYTHONHASHSEED`, the iteration order of this dictionary becomes random. This means that on successive runs, test 12.1.x might be instead called 12.3.x, or 12.5.x, etc. This also makes it difficult to figure out what these tests do via source inspection, because the order the cases are listed in the source doesn't match the order they're iterated:

```
>>> {"gutenberg_faust": None, "lena512": None, "ooms": None, "json_data1": None, "html_data1": None}
{'json_data1': None, 'lena512': None, 'gutenberg_faust': None, 'html_data1': None, 'ooms': None}
```

We hit this because `tox` now enables hash randomization by default, to match the default behavior in python 3.3-3.5. In 3.6+, dicts changed again to become order-preserving, but that still doesn't match the 2.7 behavior here. So while disabling hash randomization is a possible workaround for now, autobahn-testsuite will eventually have to deal with this when it's ported to python 3.

The `WS_COMPRESSION_TESTDATA` dict should be replaced by a list of tuples that match the traditional non-randomized python 2 ordering of this dict, and other tests should be checked as well to see if any of them rely on dict iteration order.

Originally diagnosed here: https://github.com/crossbario/autobahn-testsuite/issues/71#issuecomment-377730063

**Comment by njsmith** [comment]
Using `sorted` would make the names stable going forward, and would have been a good solution if it had been done that way to start with, but at this point it would also change all the names from the ones they've had all along...

**Comment by oberstet** [comment]
@njsmith ok, I see. the change above should do what you requested (if not, pls let me know)
