### ISSUE TITLE
Close codes 1014 and 1015 are valid

### ISSUE THREAD

**Issue by marci4** [crossbario/autobahn-testsuite#88]
Two new close codes are allowed, which are not covered by the testsuite/cause a failed test case.

- 1014 `The server was acting as a gateway or proxy and received an invalid response from the upstream server. This is similar to 502 HTTP Status Code.`
- 1015 `TLS handshake`

See https://www.iana.org/assignments/websocket/websocket.xml

Best regards,
marci4

**Comment by oberstet** [comment]
yeah, a late addition to the spec or in a revised one .. didn't have time to follow up changes after the initial publication of RFC6455 really. so good!

**Comment by theturtle32** [comment]
Why is this update not included in the Docker image?
