### ISSUE TITLE
Cut a new release ?

### ISSUE THREAD

**Issue by normanmaurer** [crossbario/autobahn-testsuite#91]
Hi @oberstet ... would it be possible to cut a new release for us to use in Netty as we would like to have  
https://github.com/crossbario/autobahn-testsuite/commit/516497949597a2e6dea04e128b816c0c78f080aa :) ?

**Comment by oberstet** [comment]
Hi Norman, sure;) https://pypi.org/project/autobahntestsuite/0.8.1/

**Comment by normanmaurer** [comment]
@oberstet thanks!
